require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BunchesController do

  # This should return the minimal set of attributes required to create a valid
  # Bunch. As you add validations to Bunch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "landing" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BunchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bunches as @bunches" do
      bunch = Bunch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bunches).should eq([bunch])
    end
  end

  describe "GET show" do
    it "assigns the requested bunch as @bunch" do
      bunch = Bunch.create! valid_attributes
      get :show, {:id => bunch.to_param}, valid_session
      assigns(:bunch).should eq(bunch)
    end
  end

  describe "GET new" do
    it "assigns a new bunch as @bunch" do
      get :new, {}, valid_session
      assigns(:bunch).should be_a_new(Bunch)
    end
  end

  describe "GET edit" do
    it "assigns the requested bunch as @bunch" do
      bunch = Bunch.create! valid_attributes
      get :edit, {:id => bunch.to_param}, valid_session
      assigns(:bunch).should eq(bunch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bunch" do
        expect {
          post :create, {:bunch => valid_attributes}, valid_session
        }.to change(Bunch, :count).by(1)
      end

      it "assigns a newly created bunch as @bunch" do
        post :create, {:bunch => valid_attributes}, valid_session
        assigns(:bunch).should be_a(Bunch)
        assigns(:bunch).should be_persisted
      end

      it "redirects to the created bunch" do
        post :create, {:bunch => valid_attributes}, valid_session
        response.should redirect_to(Bunch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bunch as @bunch" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bunch.any_instance.stub(:save).and_return(false)
        post :create, {:bunch => { "landing" => "invalid value" }}, valid_session
        assigns(:bunch).should be_a_new(Bunch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bunch.any_instance.stub(:save).and_return(false)
        post :create, {:bunch => { "landing" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bunch" do
        bunch = Bunch.create! valid_attributes
        # Assuming there are no other bunches in the database, this
        # specifies that the Bunch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bunch.any_instance.should_receive(:update).with({ "landing" => "MyText" })
        put :update, {:id => bunch.to_param, :bunch => { "landing" => "MyText" }}, valid_session
      end

      it "assigns the requested bunch as @bunch" do
        bunch = Bunch.create! valid_attributes
        put :update, {:id => bunch.to_param, :bunch => valid_attributes}, valid_session
        assigns(:bunch).should eq(bunch)
      end

      it "redirects to the bunch" do
        bunch = Bunch.create! valid_attributes
        put :update, {:id => bunch.to_param, :bunch => valid_attributes}, valid_session
        response.should redirect_to(bunch)
      end
    end

    describe "with invalid params" do
      it "assigns the bunch as @bunch" do
        bunch = Bunch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bunch.any_instance.stub(:save).and_return(false)
        put :update, {:id => bunch.to_param, :bunch => { "landing" => "invalid value" }}, valid_session
        assigns(:bunch).should eq(bunch)
      end

      it "re-renders the 'edit' template" do
        bunch = Bunch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bunch.any_instance.stub(:save).and_return(false)
        put :update, {:id => bunch.to_param, :bunch => { "landing" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bunch" do
      bunch = Bunch.create! valid_attributes
      expect {
        delete :destroy, {:id => bunch.to_param}, valid_session
      }.to change(Bunch, :count).by(-1)
    end

    it "redirects to the bunches list" do
      bunch = Bunch.create! valid_attributes
      delete :destroy, {:id => bunch.to_param}, valid_session
      response.should redirect_to(bunches_url)
    end
  end

end
